SELECT COUNT(*) AS count
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dv_Link_InvoiceLine'
AND COLUMN_NAME IN ('TRACK_INVOICE_HK', 'TRACK_HK', 'INVOICE_HK',  'LOAD_DATE', 'RECORD_SOURCE')
HAVING COUNT(*) != 5